/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout.index'
import { Route as LayoutAboutImport } from './routes/_layout.about'
import { Route as LayoutAuthImport } from './routes/_layout._auth'
import { Route as LayoutAuthUsuarioImport } from './routes/_layout._auth/_usuario'
import { Route as LayoutAuthUsuarioProfileIndexImport } from './routes/_layout._auth/_usuario.profile/index'
import { Route as LayoutAuthUsuarioDashboardIndexImport } from './routes/_layout._auth/_usuario.dashboard/index'
import { Route as LayoutAuthUsuarioProfileEditImport } from './routes/_layout._auth/_usuario.profile/edit'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthUsuarioRoute = LayoutAuthUsuarioImport.update({
  id: '/_usuario',
  getParentRoute: () => LayoutAuthRoute,
} as any)

const LayoutAuthUsuarioProfileIndexRoute =
  LayoutAuthUsuarioProfileIndexImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => LayoutAuthUsuarioRoute,
  } as any)

const LayoutAuthUsuarioDashboardIndexRoute =
  LayoutAuthUsuarioDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => LayoutAuthUsuarioRoute,
  } as any)

const LayoutAuthUsuarioProfileEditRoute =
  LayoutAuthUsuarioProfileEditImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => LayoutAuthUsuarioRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_auth/_usuario': {
      id: '/_layout/_auth/_usuario'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthUsuarioImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_auth/_usuario/profile/edit': {
      id: '/_layout/_auth/_usuario/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof LayoutAuthUsuarioProfileEditImport
      parentRoute: typeof LayoutAuthUsuarioImport
    }
    '/_layout/_auth/_usuario/dashboard/': {
      id: '/_layout/_auth/_usuario/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthUsuarioDashboardIndexImport
      parentRoute: typeof LayoutAuthUsuarioImport
    }
    '/_layout/_auth/_usuario/profile/': {
      id: '/_layout/_auth/_usuario/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthUsuarioProfileIndexImport
      parentRoute: typeof LayoutAuthUsuarioImport
    }
  }
}

// Create and export the route tree

interface LayoutAuthUsuarioRouteChildren {
  LayoutAuthUsuarioProfileEditRoute: typeof LayoutAuthUsuarioProfileEditRoute
  LayoutAuthUsuarioDashboardIndexRoute: typeof LayoutAuthUsuarioDashboardIndexRoute
  LayoutAuthUsuarioProfileIndexRoute: typeof LayoutAuthUsuarioProfileIndexRoute
}

const LayoutAuthUsuarioRouteChildren: LayoutAuthUsuarioRouteChildren = {
  LayoutAuthUsuarioProfileEditRoute: LayoutAuthUsuarioProfileEditRoute,
  LayoutAuthUsuarioDashboardIndexRoute: LayoutAuthUsuarioDashboardIndexRoute,
  LayoutAuthUsuarioProfileIndexRoute: LayoutAuthUsuarioProfileIndexRoute,
}

const LayoutAuthUsuarioRouteWithChildren =
  LayoutAuthUsuarioRoute._addFileChildren(LayoutAuthUsuarioRouteChildren)

interface LayoutAuthRouteChildren {
  LayoutAuthUsuarioRoute: typeof LayoutAuthUsuarioRouteWithChildren
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthUsuarioRoute: LayoutAuthUsuarioRouteWithChildren,
}

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutAuthUsuarioRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/': typeof LayoutIndexRoute
  '/profile/edit': typeof LayoutAuthUsuarioProfileEditRoute
  '/dashboard': typeof LayoutAuthUsuarioDashboardIndexRoute
  '/profile': typeof LayoutAuthUsuarioProfileIndexRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutAuthUsuarioRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/': typeof LayoutIndexRoute
  '/profile/edit': typeof LayoutAuthUsuarioProfileEditRoute
  '/dashboard': typeof LayoutAuthUsuarioDashboardIndexRoute
  '/profile': typeof LayoutAuthUsuarioProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_auth': typeof LayoutAuthRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_auth/_usuario': typeof LayoutAuthUsuarioRouteWithChildren
  '/_layout/_auth/_usuario/profile/edit': typeof LayoutAuthUsuarioProfileEditRoute
  '/_layout/_auth/_usuario/dashboard/': typeof LayoutAuthUsuarioDashboardIndexRoute
  '/_layout/_auth/_usuario/profile/': typeof LayoutAuthUsuarioProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/' | '/profile/edit' | '/dashboard' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/about' | '/' | '/profile/edit' | '/dashboard' | '/profile'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_auth'
    | '/_layout/about'
    | '/_layout/'
    | '/_layout/_auth/_usuario'
    | '/_layout/_auth/_usuario/profile/edit'
    | '/_layout/_auth/_usuario/dashboard/'
    | '/_layout/_auth/_usuario/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_auth",
        "/_layout/about",
        "/_layout/"
      ]
    },
    "/_layout/_auth": {
      "filePath": "_layout._auth.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_auth/_usuario"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout.about.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_auth/_usuario": {
      "filePath": "_layout._auth/_usuario.tsx",
      "parent": "/_layout/_auth",
      "children": [
        "/_layout/_auth/_usuario/profile/edit",
        "/_layout/_auth/_usuario/dashboard/",
        "/_layout/_auth/_usuario/profile/"
      ]
    },
    "/_layout/_auth/_usuario/profile/edit": {
      "filePath": "_layout._auth/_usuario.profile/edit.tsx",
      "parent": "/_layout/_auth/_usuario"
    },
    "/_layout/_auth/_usuario/dashboard/": {
      "filePath": "_layout._auth/_usuario.dashboard/index.tsx",
      "parent": "/_layout/_auth/_usuario"
    },
    "/_layout/_auth/_usuario/profile/": {
      "filePath": "_layout._auth/_usuario.profile/index.tsx",
      "parent": "/_layout/_auth/_usuario"
    }
  }
}
ROUTE_MANIFEST_END */
